// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5lVC-hXUSjpPkjS_c6evDPiDQVX4OWT8',
    appId: '1:856597764940:web:7b8824aef1a7a882ce4de9',
    messagingSenderId: '856597764940',
    projectId: 'paysar-b8a0f',
    authDomain: 'paysar-b8a0f.firebaseapp.com',
    storageBucket: 'paysar-b8a0f.appspot.com',
    measurementId: 'G-VND2TNQJB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTCrLr_snnEXoCNRb6nX_NHM0ZAW9lspA',
    appId: '1:856597764940:android:e8f5d94ce9062bbdce4de9',
    messagingSenderId: '856597764940',
    projectId: 'paysar-b8a0f',
    storageBucket: 'paysar-b8a0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWEUjk5XmSstedNJbJvGMXrdVSuwWS71E',
    appId: '1:856597764940:ios:38182785eea6fda1ce4de9',
    messagingSenderId: '856597764940',
    projectId: 'paysar-b8a0f',
    storageBucket: 'paysar-b8a0f.appspot.com',
    iosClientId: '856597764940-vo0ug65t8kn6ivfp7bilsmdhs6dvs3o4.apps.googleusercontent.com',
    iosBundleId: 'com.example.paysar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWEUjk5XmSstedNJbJvGMXrdVSuwWS71E',
    appId: '1:856597764940:ios:38182785eea6fda1ce4de9',
    messagingSenderId: '856597764940',
    projectId: 'paysar-b8a0f',
    storageBucket: 'paysar-b8a0f.appspot.com',
    iosClientId: '856597764940-vo0ug65t8kn6ivfp7bilsmdhs6dvs3o4.apps.googleusercontent.com',
    iosBundleId: 'com.example.paysar',
  );
}
